#!/bin/bash

# Script para configurar Branch Protection Rules
# Este script proporciona los comandos y enlaces necesarios

echo "🔒 CONFIGURACIÓN DE BRANCH PROTECTION RULES"
echo "============================================"
echo ""

echo "📋 PASO 1: Configurar Branch Protection para 'main'"
echo "---------------------------------------------------"
echo ""
echo "1. Abre este enlace en tu navegador:"
echo "   https://github.com/Real-Chamali/eventos-web/settings/branches"
echo ""
echo "2. Haz clic en 'Add rule'"
echo ""
echo "3. En 'Branch name pattern', escribe: main"
echo ""
echo "4. Activa estas opciones:"
echo "   ✅ Require a pull request before merging"
echo "      - Require approvals: 1"
echo "      - Dismiss stale pull request approvals when new commits are pushed"
echo ""
echo "   ✅ Require status checks to pass before merging"
echo "      - Require branches to be up to date before merging"
echo "      - Status checks: test, build, security"
echo ""
echo "   ✅ Require conversation resolution before merging"
echo ""
echo "   ✅ Do not allow bypassing the above settings"
echo ""
echo "   ❌ Allow force pushes: NO"
echo "   ❌ Allow deletions: NO"
echo ""
echo "5. Haz clic en 'Create'"
echo ""
echo ""

echo "📋 PASO 2: Configurar Branch Protection para 'develop'"
echo "------------------------------------------------------"
echo ""
echo "1. En la misma página, haz clic en 'Add rule' otra vez"
echo ""
echo "2. En 'Branch name pattern', escribe: develop"
echo ""
echo "3. Activa estas opciones:"
echo "   ✅ Require a pull request before merging"
echo "      - Require approvals: 0"
echo ""
echo "   ✅ Require status checks to pass before merging"
echo "      - Require branches to be up to date before merging"
echo "      - Status checks: test, build"
echo ""
echo "   ⚠️  Allow force pushes: Solo para admins"
echo ""
echo "   ❌ Allow deletions: NO"
echo ""
echo "4. Haz clic en 'Create'"
echo ""
echo ""

echo "✅ ¡Configuración completada!"
echo ""
echo "Verifica que ambas reglas aparezcan en la lista de 'Branch protection rules'"
echo ""

